Optional scout js script
yajra/laravel-datatables-html pull request #210
Opened 2023-10-27 23:03 UTC by frknakk

See yajra/laravel-datatables#3082

Added general system to include additional js scripts to the initialization and added specific (optional) scout addition for abovementioned pull request.

Usage:
```php
public function html(): HtmlBuilder
{
	return $this->builder()
		->setTableId('products-table')
		->addScript('datatables::scout');
}
```

2023-11-03 00:43 UTC, yajra requested changes
I like your idea on `addScipt` 🎉

- Minor change to adapt the configurable namespace
- Can we also include the scripts on the editor template

2023-11-03 00:43 UTC, yajra commented on src/resources/views/scout.blade.php
> +        let table = LaravelDataTables[$(this).attr('id')];
```suggestion
        let table = {{ config('datatables-html.namespace', 'LaravelDataTables') }}[$(this).attr('id')];
```

2023-11-03 01:06 UTC, frknakk commented
> Can we also include the scripts on the editor template

Do you mean include the same scripts a second time? If yes, why?

Or are you talking about the option to generally add scripts to editor template for future use cases?

2023-11-03 01:44 UTC, yajra commented
I mean to include the `@foreach(scripts)` inside `editor.blade.php`. We heavily use the Editor library for CRUD and I think this is a great addition to add scripts on it. Thanks!

2023-11-03 10:04 UTC, yajra approved these changes

2023-11-03 10:05 UTC, yajra commented
This is good to go, Editor support can be added on the next iteration.

2023-11-03 10:07 UTC, merged

2023-11-04 01:31 UTC, yajra commented
Released on v10.10.0 🚀 Thanks!